title: Elixeum Tech Blog
email: hello@elixeum.com
description: >-
  Technical blog from Elixeum development team, sharing our findings, ideas and solutions to problems which we have encountered.
#twitter_username: Elixeum
github_username: Elixeum
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
excerpt_separator: "<!--more-->"

# Outputting
permalink: /post/:title:output_ext
paginate: 10
paginate_path: /page:num/
timezone: Europe/Prague # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Elixeum"
  avatar : "/assets/images/logo.png"
  bio    : "Tech blog to share our findings, ideas and solutions to problems which we have encountered during our journey 🤖 🤓"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.elixeum.com"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/Elixeum"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Elixeum"

footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Elixeum"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

compress_html:
  clippings: all
  ignore:
    envs: development

category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/
